# Basic dependabot.yml file with 
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for ruby/bundler
  - package-ecosystem: "bundler"
    # Look for `Gemfile` and `Gemfile.lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Only allow updates to the lockfile for pip and
    # ignore any version updates that affect the manifest
    versioning-strategy: lockfile-only
